// Generated by scripts/bridge/generate.mjs. Do not edit by hand.
import Foundation

public enum StarhavenProtocol {
    public static let version = 1
    public static let nativeToGameTypes: Set<String> = [
        "host.ready",
        "safeArea.changed",
        "settings.changed",
        "match.start",
        "match.pause",
        "match.resume",
        "match.rematch",
        "lifecycle.background",
        "lifecycle.foreground",
        "snapshot.request",
        "snapshot.ack",
        "match.restore"
    ]
    public static let gameToNativeTypes: Set<String> = [
        "runtime.ready",
        "ack",
        "feedback.haptic",
        "pause.requested",
        "match.started",
        "match.snapshot",
        "match.ended",
        "returnMenu.requested",
        "restore.completed",
        "protocol.error",
        "pack.channel",
        "pack.reload"
    ]
}
