// Generated by scripts/bridge/generate.mjs. Do not edit by hand.
export const PROTOCOL_VERSION = 1 as const;
export const NATIVE_TO_GAME_TYPES = ["host.ready", "safeArea.changed", "settings.changed", "match.start", "match.pause", "match.resume", "match.rematch", "lifecycle.background", "lifecycle.foreground", "snapshot.request", "snapshot.ack", "match.restore"] as const;
export const GAME_TO_NATIVE_TYPES = ["runtime.ready", "ack", "feedback.haptic", "pause.requested", "match.started", "match.snapshot", "match.ended", "returnMenu.requested", "restore.completed", "protocol.error"] as const;
export type NativeToGameType = (typeof NATIVE_TO_GAME_TYPES)[number];
export type GameToNativeType = (typeof GAME_TO_NATIVE_TYPES)[number];
export type BridgeSource = "native" | "game";
export interface BridgeEnvelope<TType extends string = string, TPayload = unknown> { version: 1; id: string; sequence: number; source: BridgeSource; type: TType; matchId?: string; payload: TPayload; }
