import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const repositoryRoot = resolve(import.meta.dirname, "..", "..");
const schema = JSON.parse(readFileSync(resolve(repositoryRoot, "bridge", "protocol.v1.json"), "utf8"));
const quote = (values) => values.map((value) => JSON.stringify(value)).join(", ");
const output = `// Generated by scripts/bridge/generate.mjs. Do not edit by hand.\nexport const PROTOCOL_VERSION = ${schema.version} as const;\nexport const NATIVE_TO_GAME_TYPES = [${quote(schema.nativeToGame)}] as const;\nexport const GAME_TO_NATIVE_TYPES = [${quote(schema.gameToNative)}] as const;\nexport type NativeToGameType = (typeof NATIVE_TO_GAME_TYPES)[number];\nexport type GameToNativeType = (typeof GAME_TO_NATIVE_TYPES)[number];\nexport type BridgeSource = "native" | "game";\nexport interface BridgeEnvelope<TType extends string = string, TPayload = unknown> { version: 1; id: string; sequence: number; source: BridgeSource; type: TType; matchId?: string; payload: TPayload; }\n`;
const target = resolve(repositoryRoot, "src", "bridge", "protocol.generated.ts");
writeFileSync(target, output);
const swiftStringArray = (values) => values.map((value) => `        ${JSON.stringify(value)}`).join(",\n");
const swiftOutput = `// Generated by scripts/bridge/generate.mjs. Do not edit by hand.\nimport Foundation\n\npublic enum StarhavenProtocol {\n    public static let version = ${schema.version}\n    public static let nativeToGameTypes: Set<String> = [\n${swiftStringArray(schema.nativeToGame)}\n    ]\n    public static let gameToNativeTypes: Set<String> = [\n${swiftStringArray(schema.gameToNative)}\n    ]\n}\n`;
const swiftTarget = resolve(repositoryRoot, "ios", "Starhaven", "Bridge", "ProtocolGenerated.swift");
try {
  writeFileSync(swiftTarget, swiftOutput);
  console.log(`${target}\n${swiftTarget}`);
} catch (error) {
  if (error?.code !== "ENOENT") throw error;
  console.log(target);
}
